title: Agility - Effective Programming
description: >
  Topics on Agile and Agility
baseurl: "/agility"
url: "http://effectiveprogramming.github.io"
twitter_username: LutherBaker
github_username:  LutherBaker

# Build settings
markdown: kramdown
