title: Agility - Effective Programming
description: > # this means to ignore newlines until "baseurl:"
  Topics on agility
baseurl: "/agility" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: LutherBaker
github_username:  LutherBaker

# Build settings
markdown: kramdown
